### ISSUE TITLE
Compatibility issue with the module UIscaler

### ISSUE THREAD

**Issue by ICronyI** [pplans/foundry-vtt-module-motion-tracker#82]
When using UI Scaler (i'm on foundry v11 still), as of latest update, when i click on the motion tracker icon, nothing pops up

Here's the error code from the console in chrome:
```
uiscaler.js:86 Uncaught (in promise) TypeError: Cannot create property 'scale' on boolean 'true'
    at MotionTrackerWindow.applicationRender (uiscaler.js:86:17)
    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:616:16)
    at 🎁Application.prototype.render#0 (libWrapper-wrapper.js:189:20)
    at MotionTracker.open (motion_tracker.js:332:21)
    at MotionTracker.toggle (motion_tracker.js:367:9)
    at HTMLLIElement.<anonymous> (motion_tracker.js:41:25)
    at HTMLLIElement.dispatch (jquery.min.js:2:43184)
    at y.handle (jquery.min.js:2:41168)
applicationRender @ uiscaler.js:86
🎁call_wrapper @ libWrapper-wrapper.js:616
🎁Application.prototype.render#0 @ libWrapper-wrapper.js:189
open @ motion_tracker.js:332
toggle @ motion_tracker.js:367
(anonymous) @ motion_tracker.js:41
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2
```

Dunno if it's in your ability to fix, or if i should take it to the UIscaler guys
Thanks in advance!

**Comment by pplans** [comment]
Hello, sorry to answer this late, I'll take a look! Thanks for reporting
